title: Chanjun Park
url: "https://github.com/Parkchanjun"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "CV"
   link: "Curriculum_Vitae_Chanjunpark.pdf"

remote_theme: ankitsultana/researcher@gem

theme: jekyll-theme-minimal